name: Deploy API

on:
  pull_request:
    types:
      - closed
    branches: [main, development]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      working-directory: backend
      run: |
        python -m pip install -r requirements.txt

    - name: Generate config.json
      working-directory: backend
      run: |
        cat <<EOF > .chalice/config.json
        {
          "version": "2.0",
          "app_name": "mycity-api",
          "environment_variables": {
            "USER_POOL_ID": "${{ secrets.USER_POOL_ID }}",
            "REST_API_AUTHORIZER": "${{ secrets.REST_API_AUTHORIZER }}",
            "USER_POOL_ARN": "${{ secrets.USER_POOL_ARN }}"
          },
          "stages": {
            "dev": {
              "api_gateway_stage": "dev",
              "environment_variables": {
                "API_ENV": "${{ secrets.API_DEV_STAGE_ENV }}"
              }
            },
            "prod": {
              "api_gateway_stage": "prod",
              "environment_variables": {
                "API_ENV": "${{ secrets.API_PROD_STAGE_ENV }}"
              }
            }
          }
        }
        EOF


    - name: Set up AWS CLI
      working-directory: backend
      run: |
        pip install awscli
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region ${{ secrets.AWS_REGION }}


    - name: Set API Stage Name
      working-directory: backend
      run: |
          if [ ${{ github.base_ref }} == 'main' ]; then
            echo "API_STAGE_NAME=prod" >> $GITHUB_ENV
          elif [ ${{ github.base_ref }} == 'development' ]; then
            echo "API_STAGE_NAME=dev" >> $GITHUB_ENV
          else
            echo "No Chalice deployment for this branch"
            exit 0
          fi

    - name: Set Binary Media Types for API Gateway
      working-directory: backend
      run: |
            aws apigateway update-rest-api \
              --rest-api-id $(aws apigateway get-rest-apis --query "items[?name=='mycity-api'].id" --output text) \
              --patch-operations op=add,path=/binaryMediaTypes/multipart~1form-data

    - name: Wait Before Deploying API Gateway Stage
      working-directory: backend
      run: sleep 30  # Wait for 30 seconds before the next step

    - name: Deploy API Gateway Stage
      working-directory: backend
      run: |
          if [ ${{ github.base_ref }} == 'main' ]; then
            aws apigateway create-deployment \
          --rest-api-id ${{ secrets.API_ID }} \
          --stage-name "prod"
          elif [ ${{ github.base_ref }} == 'development' ]; then
            aws apigateway create-deployment \
          --rest-api-id ${{ secrets.API_ID }} \
          --stage-name "dev"
          else
            echo "No API Gateway Stage deployment for this branch"
            exit 0
          fi


    - name: Deploy Chalice App
      working-directory: backend
      run: |
          chalice deploy --stage ${{ env.API_STAGE_NAME }}


    - name: Update API Gateway
      working-directory: backend/.chalice
      env:
        API_STAGE_NAME: ${{ env.API_STAGE_NAME }}
      run: python update_api_gateway.py