name: Deploy API

on:
  pull_request:
    types:
      - closed
    branches: [development]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      working-directory: mycity-backend
      run: |
        python -m pip install -r requirements.txt

    - name: Set up AWS CLI
      working-directory: mycity-backend
      run: |
        pip install awscli
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region ${{ secrets.AWS_REGION }}

    - name: Deploy Chalice App
      working-directory: mycity-backend
      run: chalice deploy
