name: Deploy API

on:
  pull_request:
    types:
      - closed
    branches: [main, development]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      working-directory: backend
      run: |
        python -m pip install -r requirements.txt

    - name: Update config.json
      working-directory: backend
      run: |
        echo ${{ secrets.CHALICE_CONFIG_JSON }} > .chalice/config.json

    - name: Deploy Chalice App
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      working-directory: backend
      run: |
          if [ ${{ github.base_ref }} == 'main' ]; then
            chalice deploy --stage prod
          elif [ ${{ github.base_ref }} == 'development' ]; then
            chalice deploy --stage dev
          else
            echo "No deployment for this branch"
            exit 0
          fi
