name: Super Linter

on:
  pull_request:
    branches: [main, development, release]
  workflow_dispatch: {}

jobs:
  build:
    name: Super Linter

    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Cache Super-Linter dependencies
      - name: Cache Super-Linter files
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/linters
            ~/.cache/superlinter
          key: ${{ runner.os }}-superlinter-${{ hashFiles('**/.github/workflows/superlinter.yml') }}
          restore-keys: |
            ${{ runner.os }}-superlinter-

      - name: Super-Linter
        uses: super-linter/super-linter@v6.5.1
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON_BLACK: true
          IGNORE_GITIGNORED_FILES: true
          IGNORE_GENERATED_FILES: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}