name: Super-Linter

on: 
  pull_request:
      branches: [main, release, development]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Super-Linter
      uses: super-linter/super-linter@v6.5.1
      env:
        VALIDATE_ALL_CODEBASE: false
        VALIDATE_PYTHON_BLACK: true
        IGNORE_GITIGNORED_FILES: true
        IGNORE_GENERATED_FILES: true
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
